exclude: "^.*(migrations|fluent_comments).*$"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.37.3
    hooks:
      - id: pyupgrade
        args: [--py310-plus]
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.7.0
    hooks:
      - id: django-upgrade
        args: [--target-version, "4.1"]
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        language_version: python3.10

  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
        language_version: python3
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        entry: pflake8
        language_version: python3
        additional_dependencies: [pyproject-flake8]
  - repo: https://github.com/rtts/djhtml
    rev: "v1.5.1"  # replace with the latest tag on GitHub
    hooks:
      - id: djhtml
        args: [-t, "2"]
