# postgres: postgres -D databases/postgres
# web: PYTHONUNBUFFERED=true ~/.virtualenvs/foo/bin/python manage.py runserver 0.0.0.0:8000 --settings=config.settings.development
# notebook: python commands.py jupyterlab
