# postgres: postgres -D databases/postgres
# web: PYTHONUNBUFFERED=true ~/.virtualenvs/foo/bin/python manage.py runserver 0.0.0.0:8000 --settings=config.settings.development
# notebook: DJANGO_ALLOW_ASYNC_UNSAFE=true DJANGO_SETTINGS_MODULE=config.settings.development python manage.py shell_plus --notebook
