all:
  vars:
    ansible_connection: ssh
    ansible_ssh_user: root
  hosts:
    production:
      ansible_host: 127.0.0.1  # staging.wersdoerfer.de
  children:
    webservers:
      hosts:
        production:
    database:
      hosts:
        production:
